### ISSUE TITLE
Not picking up AZ Login

### ISSUE THREAD

**Issue by karlrissland** [JanneMattila/azure-api-management-developer-portal-action#1]
I am successfully logging into azure with the azure/login@v1 task.  I am running ```az account show``` to validate that I am indeed logged in and it works successfully.  However, when I run your task, it fails.

![image](https://github.com/JanneMattila/azure-api-management-developer-portal-action/assets/9871029/ef7ccfc3-4fb4-4bd4-86c1-2f4266357674)

![image](https://github.com/JanneMattila/azure-api-management-developer-portal-action/assets/9871029/a31f5026-8373-47ae-aabf-fa8c998ae875)

**Comment by karlrissland** [comment]
Taking a look at the powershell script, I noticed that you are using Get-AzContext.  I tried this in my local terminal window and got the following error

![image](https://github.com/JanneMattila/azure-api-management-developer-portal-action/assets/9871029/988fd3f6-bba6-4eb3-afb8-4829b57b88da)

When I run that command in a workflow, it errors out
![image](https://github.com/JanneMattila/azure-api-management-developer-portal-action/assets/9871029/ed0bc4fc-0dda-45e1-8bf9-037a244f7642)

This is on line 173 in the apim-import-export.ps1 file

**Comment by karlrissland** [comment]
I have a workaround!

I ran the following before trying to export the dev portal

![image](https://github.com/JanneMattila/azure-api-management-developer-portal-action/assets/9871029/ca396350-6102-46f0-8541-e1a4ccbcf1f4)

This seems to do the trick.

**Comment by JanneMattila** [comment]
I wonder if something has changed. Looking at [Azure PowerShell Action](https://github.com/marketplace/actions/azure-powershell-action) I can see that this should do the trick:

```yaml
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
```

Of course, `enable-AzPSSession: true` being the key part of the action. 

But glad that you got that sorted out!

**Comment by karlrissland** [comment]
Yeah, not sure what's up, but it works.... was able to export everything just fine.  Thanks for the help.
