### ISSUE TITLE
Error if no media folder - text doesn't support text only customizations

### ISSUE THREAD

**Issue by karlrissland** [JanneMattila/azure-api-management-developer-portal-action#2]
Text only customizations creates an empty media folder.  Depending on how the branch has been created, that folder may or may not exist since it is empty.

![image](https://github.com/JanneMattila/azure-api-management-developer-portal-action/assets/9871029/869339ee-4322-41f9-bc2a-ee73bd05cb57)

**Comment by karlrissland** [comment]
Workaround: add the following code before calling the action

```
      - run: |
          If(!(Test-Path -path "${{env.OUTPUT_FOLDER}}/Media/"))
          {
            #if it does not create it
            Write-Host "creating Media Folder"
            mkdir ${{env.OUTPUT_FOLDER}}/Media
            dir ${{env.OUTPUT_FOLDER}}
          }
        shell: pwsh
```

env.OUTPUT_FOLDER is the folder that contains the data.json file.

**Comment by JanneMattila** [comment]
I just realized that I had [demo](https://github.com/JanneMattila/github-actions-demos/blob/main/.github/workflows/azure-api-management.yml) workflow. 

@karlrissland is that structure from my demo workflow something that doesn't work anymore? If that's the case, then I'll have to check those scripts and update them accordingly. It's not nice to have these workarounds.

**Comment by JanneMattila** [comment]
I created improvements based on your feedback. I also noticed that if you have custom widgets then the export didn't properly handle the folder structure. 

If you have @karlrissland chance to test v2, then that would be valuable.

**Comment by karlrissland** [comment]
I will take a look.... thanks.
